# Generated by Django 3.2.18 on 2023-04-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satbotTA', '0002_auto_20230401_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['user', 'timestamp', 'course']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['class_title']},
        ),
        migrations.AlterModelOptions(
            name='incompletequestion',
            options={'ordering': ['estimated_intent']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
