# Generated by Django 3.2.18 on 2023-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satbotTA', '0005_auto_20230403_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(choices=[('U', 'User'), ('B', 'Bot')], default='U', max_length=1),
        ),
    ]
