# Generated by Django 4.2 on 2023-05-03 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satbotTA', '0006_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intents', to='satbotTA.user'),
        ),
    ]
