# Generated by Django 4.2 on 2023-05-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satbotTA', '0007_intent_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='intent_type',
            field=models.CharField(choices=[('P', 'Public'), ('L', 'Local')], default='L', max_length=1),
        ),
    ]
