# Generated by Django 4.2.1 on 2023-05-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satbotTA', '0008_intent_intent_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incompletequestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='incompletequestion',
            name='estimated_intent',
        ),
    ]
