# Generated by Django 4.2.1 on 2023-05-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satbotTA', '0009_alter_incompletequestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
